### PR TITLE
Fixes for problems found during testing of release candidate 1

### LINKED ISSUE #19: Issues while installing
When executing
```
cd ~/rt-data-collection-application-function
meson test -C build regression
```
I obtain the following log. It complains about a declare. I understood declare is for bash and not for sh but not sure what is the alternative for a "declare -n"
```
==================================== 1/1 =====================================
test:         rt-data-collection-application-function / regression
start time:   07:34:34
duration:     3.01s
result:       exit status 2
command:      MALLOC_PERTURB_=83 UBSAN_OPTIONS=halt_on_error=1:abort_on_error=1:print_summary=1:print_stacktrace=1 ASAN_OPTIONS=halt_on_error=1:abort_on_error=1:print_summary=1 /home/fivegmag/rt-data-collection-application-function/tests/run_test_scripts.sh
----------------------------------- stderr -----------------------------------
/home/fivegmag/rt-data-collection-application-function/tests/run_test_scripts.sh: 70: /home/fivegmag/rt-data-collection-application-function/tests/scripts/000_prepare.sh: declare: not found
/home/fivegmag/rt-data-collection-application-function/tests/run_test_scripts.sh: 70: /home/fivegmag/rt-data-collection-application-function/tests/scripts/000_prepare.sh: declare: not found
/home/fivegmag/rt-data-collection-application-function/tests/run_test_scripts.sh: 93: Bad substitution
==============================================================================


Summary of Failures:

1/1 rt-data-collection-application-function / regression FAIL             3.01s   exit status 2

Ok:                 0   
Expected Fail:      0   
Fail:               1   
Unexpected Pass:    0   
Skipped:            0   
Timeout:            0  
```

### PR DESCRIPTION
**Pull request by davidjwbbc**
This PR fixes the following issues raised from the testing of the release candidate tagged `rt-data-collection-application-function-1.0.0-rc1`:
 - "declare" syntax error during regression testing (issue #19) : fix = Force regression tests to use Bash shell.
 - Responses not understood (issue #19): fix = Ensure curl is version 8.3.0 or better and abort tests if not. Add link to upgrade old version of curl on Ubuntu to the README.
 - `waitpid` command not found (issue #19): fix = Update README to install package which provides `waitpid`.

Closes #19

### CODE REVIEW

**Comment by dsilhavy** [comment]
Confirmed that this fixes the following issue:

````text
/home/dsi/5gmag/rt-data-collection-application-function/tests/run_test_scripts.sh: 70: /home/dsi/5gmag/rt-data-collection-application-function/tests/scripts/000_prepare.sh: declare: not found
/home/dsi/5gmag/rt-data-collection-application-function/tests/run_test_scripts.sh: 70: /home/dsi/5gmag/rt-data-collection-application-function/tests/scripts/000_prepare.sh: declare: not found
/home/dsi/5gmag/rt-data-collection-application-function/tests/run_test_scripts.sh: 93: Bad substitution
````

**Comment by jordijoangimenez** [comment]
@dsilhavy, which version of Ubuntu are you using?

**Review by jordijoangimenez — DISMISSED** [review]
I suggest we add in the readme the depencencies:
curl (with a pointer to Basically followed this guide: https://www.alphagnu.com/topic/7-install-latest-curl-version-830-on-ubuntu-22042004debian-12hestiacp/)
jq
ncat

**Comment by dsilhavy** [comment]
> I suggest we add in the readme the depencencies: curl (with a pointer to Basically followed this guide: https://www.alphagnu.com/topic/7-install-latest-curl-version-830-on-ubuntu-22042004debian-12hestiacp/) jq ncat

* ncat not required anymore
* jq is added
* Add CURL installation steps for version 8.3.0 to documentation
* Can version of CURL be checked as part of executing the regression tests? Then dispatch a warning and skip the tests.

**Comment by davidjwbbc** [comment]
> I suggest we add in the readme the depencencies: curl (with a pointer to Basically followed this guide: https://www.alphagnu.com/topic/7-install-latest-curl-version-830-on-ubuntu-22042004debian-12hestiacp/) jq ncat

I've updated the README to address a missing dependency and to link to the instructions for upgrading curl.

**Comment by jordijoangimenez** [comment]
@davidjwbbc your changes look good to me. The only issue is that util-linux-extra cannot be installed in 22.04

**Comment by davidjwbbc** [comment]
> @davidjwbbc your changes look good to me. The only issue is that util-linux-extra cannot be installed in 22.04

Looks like `waitpid` is only available in the util-linux-extra v2.39 package and Jammy is on v2.37.

**Review by dsilhavy — APPROVED** [review]

**Comment by jordijoangimenez** [comment]
Hi @davidjwbbc, sorry, I commented on the wrong thread: https://github.com/5G-MAG/rt-data-collection-application-function/issues/19#issuecomment-2544003838

**Pull request merged**
